spring:
  profiles:
    active: dev    # 默认选择dev环境
#    active: pro    # 默认选择pro环境

---
spring:
  profiles: dev
server:
  port: 8888
  servlet:
    context-path: /ddd

---
spring:
  profiles: pro
server:
  port: 9999
  servlet:
    context-path: /ppp