server:
  port: 8888
  servlet:
    context-path: /xxx

mybatis:
  # 注册映射文件
  mapper-locations: classpath:com/wangyuxuan/dao/*.xml
  # 注册实体类别名
  type-aliases-package: com.wangyuxuan.bean

# 注册数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test?useUnicode=true&characterEncoding=utf8
    username: root
    password: wangyuxuan

# Logback日志控制
logging:
  pattern:
    # 指定日志显示在控制台，并指定日志显示内容及格式
    console: logs-%level %msg%n
  level:
    root: warn    # 控制项目启动时的日志输出
    com.wangyuxuan.dao: debug    # 控制指定包中的类的执行日志